eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://84.86.167.197:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: POST-SERVICE
server:
  port: 5016

keycloak:
  realm: TacticalWolves
  resource: TacticalWolves-App
  auth-server-url: https://84.86.167.197:8082/auth
  credentials:
    secret: 95b22d8a-1696-4314-824e-192947bf39ae
  disable-trust-manager: true